WARNING    - 2024-04-02 17:41:31,625 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2024-04-02 17:41:31,628 - client          : logging in using static token
INFO       - 2024-04-02 17:41:32,304 - gateway         : Shard ID None has connected to Gateway (Session ID: c2ac823ee2bcb92e3ced02e28595344e).
ERROR      - 2024-04-02 17:41:53,210 - bot             : Ignoring exception in command x
Traceback (most recent call last):
  File "C:\Users\ericf\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericf\OneDrive\Music\Documents\discordbot\splatink\rotationcmds.py", line 30, in x
    await send_rotation_info(ctx)
  File "C:\Users\ericf\OneDrive\Music\Documents\discordbot\splatink\rotationcmds.py", line 22, in send_rotation_info
    await rotation.get_xBattles()
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ericf\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\ericf\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericf\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
